[package]
name = "pyrobase"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.22"
tui = { version = "0.16", features = ["crossterm"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"